### PR TITLE
Qt testing check

### PR DESCRIPTION
**Pull request by mwestphal**
Adding a basic check feature to QtTesting

### CODE REVIEW

**Comment by mwestphal** [comment]
@yumin @utkarshayachit @jpouderoux

**Comment by mwestphal** [comment]
@finetjul

**Comment by mwestphal** [comment]
This is a pull request to add a check fonctionality and correct different issues with QtTesting : 

- Adding a eventType EVENT / CHECK_EVENT in translateEvent and playEvent method, while keeping full retrocompatibility, and allowing further open developpement

- Adding on overlay showing which widget can be checked or not, via translateEvent MouseMove event while checking

- Adding a check fonctionnality via translateEvent mouseButtonRelease event while checking

- Adding a metaProperty based check in BasicWidgetTranslator/Player

- Generalizing TreeViewTranslator/Player into a AbstractItemViewTranslator/PlayerBase used be TreeView and TableView, with check support base on ModelIned displayRole data and rowCount.
Other AbstractItemView are still handled by AbstractItemViewTranslator/Player

- Adding a check fonctionnality for QTextEdit via html property

- Correct handling of contextMenu event in WidgetEventPlayer (base pure abstract class), all widget centric translator/player should call superclass translate/playEvent when not handling an event

- Bugfixes

- Documentation update

**Comment by mwestphal** [comment]
@yumin @utkarshayachit

**Comment by mwestphal** [comment]
@finetjul

**Comment by finetjul** [comment]
Could you squash all the commits related to the "check" feature ?
Thanks,
Julien.

**Comment by mwestphal** [comment]
Some commits are related to QtTesting design AND check feature, i can't really seperate "only check" related commits and "QtTesting design" commits. I can separate little QtTesting bug fixes commits if necessary.

**Pull request closed without merging**
